// Code generated by roost servicerpc. DO NOT EDIT.
//
// Generated from the Routing interface in this package. The interface is
// the single source of truth: the wire types, the handler table and the client
// are all derived from it, so a method added to the interface cannot be
// forgotten in the transport — the failure this generator exists to make
// impossible rather than merely detectable.
//
// Regenerate with:
//
//	go run github.com/tjbdwanghaibo/roost-codegen/cmd/servicerpc -dir .

package global

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/spf13/viper"
	"github.com/tjbdwanghaibo/roost-core/app"
	"github.com/tjbdwanghaibo/roost-core/bus"
	"github.com/tjbdwanghaibo/roost-kit/mods"
	"github.com/tjbdwanghaibo/roost-kit/servicerpc"
)

// ServiceType is the bus service type Routing answers on. The client and
// the handlers key on it, so it is one constant rather than a string in two
// places.
const ServiceType = "global"

// The RPC method names, prefixed with the service type so a bus subject is
// unambiguous when several services register handlers on one connection.
const (
	MethodBind              = "global.Bind"
	MethodResolve           = "global.Resolve"
	MethodBeginMigration    = "global.BeginMigration"
	MethodCompleteMigration = "global.CompleteMigration"
	MethodAbortMigration    = "global.AbortMigration"
	MethodAcquireLease      = "global.AcquireLease"
	MethodRenewLease        = "global.RenewLease"
	MethodReleaseLease      = "global.ReleaseLease"
	MethodLease             = "global.Lease"
	MethodLiveGames         = "global.LiveGames"
)

// Methods is every method on Routing, in interface order.
//
// RegisterHandlers iterates it, so a method with no handler fails at startup
// with a name rather than at the first call from another process.
var Methods = []string{
	MethodBind,
	MethodResolve,
	MethodBeginMigration,
	MethodCompleteMigration,
	MethodAbortMigration,
	MethodAcquireLease,
	MethodRenewLease,
	MethodReleaseLease,
	MethodLease,
	MethodLiveGames,
}

// rpcStatus is the envelope every response embeds.
//
// A business failure travels inside the envelope with this package's error
// code; a bus error means the call did not happen. A caller retrying the
// second and not the first is the difference between recovering and
// double-applying, which is why the two are never the same channel.
type rpcStatus struct {
	Code   int32  `json:"code"`
	Reason string `json:"reason,omitempty"`
}

// StatusCode implements servicerpc.ResponseStatusProvider. The methods are
// exported even though the type is not, which is what the assertion in
// servicerpc.CheckResponse needs.
func (s rpcStatus) StatusCode() int32 { return s.Code }

// StatusReason implements servicerpc.ResponseStatusProvider.
func (s rpcStatus) StatusReason() string { return s.Reason }

// statusOf renders an error using this package's Error, so a code that reaches
// a client is the same code a local caller reads off the error.
func statusOf(err error) rpcStatus {
	code, reason := Error(err)
	return rpcStatus{Code: code, Reason: reason}
}

// --- wire types ---

// rpcBindRequest is the Bind request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcBindRequest struct {
	GameSID   int32  `json:"game_sid"`
	GroupID   string `json:"group_id"`
	GlobalSID int32  `json:"global_sid"`
}

// rpcBindResponse is the Bind response on the wire.
type rpcBindResponse struct {
	rpcStatus
	Binding RouteBinding `json:"binding"`
}

// rpcResolveRequest is the Resolve request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcResolveRequest struct {
	GameSID int32 `json:"game_sid"`
}

// rpcResolveResponse is the Resolve response on the wire.
type rpcResolveResponse struct {
	rpcStatus
	Binding RouteBinding `json:"binding"`
}

// rpcBeginMigrationRequest is the BeginMigration request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcBeginMigrationRequest struct {
	GameSID         int32  `json:"game_sid"`
	TargetGlobalSID int32  `json:"target_global_sid"`
	ExpectEpoch     uint64 `json:"expect_epoch"`
}

// rpcBeginMigrationResponse is the BeginMigration response on the wire.
type rpcBeginMigrationResponse struct {
	rpcStatus
	Binding RouteBinding `json:"binding"`
}

// rpcCompleteMigrationRequest is the CompleteMigration request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcCompleteMigrationRequest struct {
	GameSID     int32  `json:"game_sid"`
	ExpectEpoch uint64 `json:"expect_epoch"`
}

// rpcCompleteMigrationResponse is the CompleteMigration response on the wire.
type rpcCompleteMigrationResponse struct {
	rpcStatus
	Binding RouteBinding `json:"binding"`
}

// rpcAbortMigrationRequest is the AbortMigration request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcAbortMigrationRequest struct {
	GameSID     int32  `json:"game_sid"`
	ExpectEpoch uint64 `json:"expect_epoch"`
}

// rpcAbortMigrationResponse is the AbortMigration response on the wire.
type rpcAbortMigrationResponse struct {
	rpcStatus
	Binding RouteBinding `json:"binding"`
}

// rpcAcquireLeaseRequest is the AcquireLease request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcAcquireLeaseRequest struct {
	GameSID int32 `json:"game_sid"`
}

// rpcAcquireLeaseResponse is the AcquireLease response on the wire.
type rpcAcquireLeaseResponse struct {
	rpcStatus
	Lease GameLease `json:"lease"`
}

// rpcRenewLeaseRequest is the RenewLease request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcRenewLeaseRequest struct {
	GameSID     int32             `json:"game_sid"`
	Incarnation string            `json:"incarnation"`
	Load        map[string]string `json:"load"`
}

// rpcRenewLeaseResponse is the RenewLease response on the wire.
type rpcRenewLeaseResponse struct {
	rpcStatus
	Lease GameLease `json:"lease"`
}

// rpcReleaseLeaseRequest is the ReleaseLease request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcReleaseLeaseRequest struct {
	GameSID     int32  `json:"game_sid"`
	Incarnation string `json:"incarnation"`
}

// rpcReleaseLeaseResponse is the ReleaseLease response on the wire.
type rpcReleaseLeaseResponse struct {
	rpcStatus
}

// rpcLeaseRequest is the Lease request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcLeaseRequest struct {
	GameSID int32 `json:"game_sid"`
}

// rpcLeaseResponse is the Lease response on the wire.
type rpcLeaseResponse struct {
	rpcStatus
	Lease GameLease `json:"lease"`
	Found bool      `json:"found"`
}

// rpcLiveGamesRequest is the LiveGames request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcLiveGamesRequest struct {
	GroupID    string  `json:"group_id"`
	Candidates []int32 `json:"candidates"`
	Limit      int     `json:"limit"`
}

// rpcLiveGamesResponse is the LiveGames response on the wire.
type rpcLiveGamesResponse struct {
	rpcStatus
	Leases []GameLease `json:"leases"`
}

// --- server ---

// RegisterHandlers publishes Routing on a bus.
//
// It is called by the process that OWNS the service. The handlers decode and
// call the local implementation and contain no logic of their own: a check
// that lived here rather than in the service would apply only to remote
// callers, and a local caller would bypass it.
func RegisterHandlers(b bus.IBus, service Routing) error {
	if b == nil {
		return fmt.Errorf("global: bus is nil")
	}
	if service == nil {
		return fmt.Errorf("global: service is nil")
	}
	handlers := map[string]bus.RpcHandlerFunc{
		MethodBind: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcBindRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcBindResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			binding, err := service.Bind(ctx.Context(), wire.GameSID, wire.GroupID, wire.GlobalSID)
			return rpcBindResponse{rpcStatus: statusOf(err), Binding: binding}, nil
		},
		MethodResolve: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcResolveRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcResolveResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			binding, err := service.Resolve(ctx.Context(), wire.GameSID)
			return rpcResolveResponse{rpcStatus: statusOf(err), Binding: binding}, nil
		},
		MethodBeginMigration: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcBeginMigrationRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcBeginMigrationResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			binding, err := service.BeginMigration(ctx.Context(), wire.GameSID, wire.TargetGlobalSID, wire.ExpectEpoch)
			return rpcBeginMigrationResponse{rpcStatus: statusOf(err), Binding: binding}, nil
		},
		MethodCompleteMigration: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcCompleteMigrationRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcCompleteMigrationResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			binding, err := service.CompleteMigration(ctx.Context(), wire.GameSID, wire.ExpectEpoch)
			return rpcCompleteMigrationResponse{rpcStatus: statusOf(err), Binding: binding}, nil
		},
		MethodAbortMigration: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcAbortMigrationRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcAbortMigrationResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			binding, err := service.AbortMigration(ctx.Context(), wire.GameSID, wire.ExpectEpoch)
			return rpcAbortMigrationResponse{rpcStatus: statusOf(err), Binding: binding}, nil
		},
		MethodAcquireLease: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcAcquireLeaseRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcAcquireLeaseResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			lease, err := service.AcquireLease(ctx.Context(), wire.GameSID)
			return rpcAcquireLeaseResponse{rpcStatus: statusOf(err), Lease: lease}, nil
		},
		MethodRenewLease: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcRenewLeaseRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcRenewLeaseResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			lease, err := service.RenewLease(ctx.Context(), wire.GameSID, wire.Incarnation, wire.Load)
			return rpcRenewLeaseResponse{rpcStatus: statusOf(err), Lease: lease}, nil
		},
		MethodReleaseLease: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcReleaseLeaseRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcReleaseLeaseResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			err := service.ReleaseLease(ctx.Context(), wire.GameSID, wire.Incarnation)
			return rpcReleaseLeaseResponse{rpcStatus: statusOf(err)}, nil
		},
		MethodLease: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcLeaseRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcLeaseResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			lease, found, err := service.Lease(ctx.Context(), wire.GameSID)
			return rpcLeaseResponse{rpcStatus: statusOf(err), Lease: lease, Found: found}, nil
		},
		MethodLiveGames: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcLiveGamesRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcLiveGamesResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			leases, err := service.LiveGames(ctx.Context(), wire.GroupID, wire.Candidates, wire.Limit)
			return rpcLiveGamesResponse{rpcStatus: statusOf(err), Leases: leases}, nil
		},
	}
	// Registered against Methods rather than by ranging the map, so a method
	// the interface declares and the table misses fails HERE, with a name.
	for _, method := range Methods {
		handler, ok := handlers[method]
		if !ok {
			return fmt.Errorf("global: no handler for %s", method)
		}
		if err := b.HandleRpc(method, handler); err != nil {
			return fmt.Errorf("global: register %s: %w", method, err)
		}
	}
	if len(handlers) != len(Methods) {
		return fmt.Errorf("global: %d handlers for %d methods", len(handlers), len(Methods))
	}
	return nil
}

// --- client ---

// DefaultCallTimeout bounds one RPC. A call with no timeout is a goroutine
// waiting on a process that may never answer.
const DefaultCallTimeout = 3 * time.Second

// BusClient is Routing over a bus, for the processes that do not own this
// service.
//
// Its method signatures are the interface's, identity included: a caller still
// has to say whose identity it is, and the wire types are this type's
// implementation detail.
type BusClient struct {
	rpc *servicerpc.BusClient
}

// NewBusClient builds a client. serviceType empty means ServiceType; timeout
// non-positive means DefaultCallTimeout.
func NewBusClient(b bus.IBus, serviceType string, timeout time.Duration, opts ...servicerpc.Option) (*BusClient, error) {
	if b == nil {
		return nil, fmt.Errorf("global: bus is nil")
	}
	if serviceType == "" {
		serviceType = ServiceType
	}
	if timeout <= 0 {
		timeout = DefaultCallTimeout
	}
	return &BusClient{rpc: servicerpc.NewBusClient(b, serviceType, timeout, opts...)}, nil
}

func (c *BusClient) call(ctx context.Context, method string, req any, resp any) error {
	if c == nil || c.rpc == nil {
		return fmt.Errorf("global: client is not configured")
	}
	return c.rpc.CallChecked(ctx, 0, method, req, resp, "global call failed")
}

// Bind establishes the first binding for a game server. It is
// insert-only: rebinding a game that already has one is refused, and a
// move goes through the migration steps instead.
// Bind implements Routing.
func (c *BusClient) Bind(ctx context.Context, gameSID int32, groupID string, globalSID int32) (RouteBinding, error) {
	var resp rpcBindResponse
	err := c.call(ctx, MethodBind, rpcBindRequest{
		GameSID:   gameSID,
		GroupID:   groupID,
		GlobalSID: globalSID,
	}, &resp)
	return resp.Binding, err
}

// Resolve reports where a game server belongs. It is the first call a
// game process makes and the one it repeats after a migration.
// Resolve implements Routing.
func (c *BusClient) Resolve(ctx context.Context, gameSID int32) (RouteBinding, error) {
	var resp rpcResolveResponse
	err := c.call(ctx, MethodResolve, rpcResolveRequest{
		GameSID: gameSID,
	}, &resp)
	return resp.Binding, err
}

// BeginMigration marks a binding as migrating toward a target, fenced on
// the epoch the caller last read.
// BeginMigration implements Routing.
func (c *BusClient) BeginMigration(ctx context.Context, gameSID int32, targetGlobalSID int32, expectEpoch uint64) (RouteBinding, error) {
	var resp rpcBeginMigrationResponse
	err := c.call(ctx, MethodBeginMigration, rpcBeginMigrationRequest{
		GameSID:         gameSID,
		TargetGlobalSID: targetGlobalSID,
		ExpectEpoch:     expectEpoch,
	}, &resp)
	return resp.Binding, err
}

// CompleteMigration finishes a migration, fenced the same way.
// CompleteMigration implements Routing.
func (c *BusClient) CompleteMigration(ctx context.Context, gameSID int32, expectEpoch uint64) (RouteBinding, error) {
	var resp rpcCompleteMigrationResponse
	err := c.call(ctx, MethodCompleteMigration, rpcCompleteMigrationRequest{
		GameSID:     gameSID,
		ExpectEpoch: expectEpoch,
	}, &resp)
	return resp.Binding, err
}

// AbortMigration returns a migrating binding to its origin.
// AbortMigration implements Routing.
func (c *BusClient) AbortMigration(ctx context.Context, gameSID int32, expectEpoch uint64) (RouteBinding, error) {
	var resp rpcAbortMigrationResponse
	err := c.call(ctx, MethodAbortMigration, rpcAbortMigrationRequest{
		GameSID:     gameSID,
		ExpectEpoch: expectEpoch,
	}, &resp)
	return resp.Binding, err
}

// AcquireLease takes the lease for a game server, minting a new
// incarnation. A previous holder's incarnation stops being able to renew.
// AcquireLease implements Routing.
func (c *BusClient) AcquireLease(ctx context.Context, gameSID int32) (GameLease, error) {
	var resp rpcAcquireLeaseResponse
	err := c.call(ctx, MethodAcquireLease, rpcAcquireLeaseRequest{
		GameSID: gameSID,
	}, &resp)
	return resp.Lease, err
}

// RenewLease is the heartbeat. The incarnation is required, so a process
// that lost the lease and did not notice cannot keep it alive.
// RenewLease implements Routing.
func (c *BusClient) RenewLease(ctx context.Context, gameSID int32, incarnation string, load map[string]string) (GameLease, error) {
	var resp rpcRenewLeaseResponse
	err := c.call(ctx, MethodRenewLease, rpcRenewLeaseRequest{
		GameSID:     gameSID,
		Incarnation: incarnation,
		Load:        load,
	}, &resp)
	return resp.Lease, err
}

// ReleaseLease gives the lease up. The incarnation is required for the
// same reason.
// ReleaseLease implements Routing.
func (c *BusClient) ReleaseLease(ctx context.Context, gameSID int32, incarnation string) error {
	var resp rpcReleaseLeaseResponse
	err := c.call(ctx, MethodReleaseLease, rpcReleaseLeaseRequest{
		GameSID:     gameSID,
		Incarnation: incarnation,
	}, &resp)
	return err
}

// Lease reads one lease without touching it.
// Lease implements Routing.
func (c *BusClient) Lease(ctx context.Context, gameSID int32) (GameLease, bool, error) {
	var resp rpcLeaseResponse
	err := c.call(ctx, MethodLease, rpcLeaseRequest{
		GameSID: gameSID,
	}, &resp)
	return resp.Lease, resp.Found, err
}

// LiveGames reports which of the candidate game servers hold a live
// lease. The candidate set is the caller's, so this is a bounded read
// rather than an enumeration.
// LiveGames implements Routing.
func (c *BusClient) LiveGames(ctx context.Context, groupID string, candidates []int32, limit int) ([]GameLease, error) {
	var resp rpcLiveGamesResponse
	err := c.call(ctx, MethodLiveGames, rpcLiveGamesRequest{
		GroupID:    groupID,
		Candidates: candidates,
		Limit:      limit,
	}, &resp)
	return resp.Leases, err
}

// --- capability ---

// capability is what a Mod puts in the registry.
//
// It exists because converting to the interface at the registration call site
// does not do what it looks like it does: `Value: Routing(x)` stores an any
// whose dynamic type is still x's — Go does not box an interface inside an
// interface — so an assertion on the concrete type succeeds anyway. Wrapping
// the interface in a struct makes the dynamic type this wrapper, which
// satisfies Routing and nothing else.
//
// The consequence is the one that matters: a consumer cannot bind to the local
// implementation and then break on the day this service moves into its own
// process.
//
// It forwards each method explicitly rather than embedding the interface, and
// that is not style. Embedding names the field after the type, so an interface
// with a method of its own name — Rank.Rank, Match.Match — would have the
// field shadow the method and the wrapper would not satisfy the interface at
// all. The second service this generator ran against had exactly that shape.
type capability struct{ inner Routing }

func (c capability) Bind(ctx context.Context, gameSID int32, groupID string, globalSID int32) (RouteBinding, error) {
	return c.inner.Bind(ctx, gameSID, groupID, globalSID)
}

func (c capability) Resolve(ctx context.Context, gameSID int32) (RouteBinding, error) {
	return c.inner.Resolve(ctx, gameSID)
}

func (c capability) BeginMigration(ctx context.Context, gameSID int32, targetGlobalSID int32, expectEpoch uint64) (RouteBinding, error) {
	return c.inner.BeginMigration(ctx, gameSID, targetGlobalSID, expectEpoch)
}

func (c capability) CompleteMigration(ctx context.Context, gameSID int32, expectEpoch uint64) (RouteBinding, error) {
	return c.inner.CompleteMigration(ctx, gameSID, expectEpoch)
}

func (c capability) AbortMigration(ctx context.Context, gameSID int32, expectEpoch uint64) (RouteBinding, error) {
	return c.inner.AbortMigration(ctx, gameSID, expectEpoch)
}

func (c capability) AcquireLease(ctx context.Context, gameSID int32) (GameLease, error) {
	return c.inner.AcquireLease(ctx, gameSID)
}

func (c capability) RenewLease(ctx context.Context, gameSID int32, incarnation string, load map[string]string) (GameLease, error) {
	return c.inner.RenewLease(ctx, gameSID, incarnation, load)
}

func (c capability) ReleaseLease(ctx context.Context, gameSID int32, incarnation string) error {
	return c.inner.ReleaseLease(ctx, gameSID, incarnation)
}

func (c capability) Lease(ctx context.Context, gameSID int32) (GameLease, bool, error) {
	return c.inner.Lease(ctx, gameSID)
}

func (c capability) LiveGames(ctx context.Context, groupID string, candidates []int32, limit int) ([]GameLease, error) {
	return c.inner.LiveGames(ctx, groupID, candidates, limit)
}

// Capability wraps a Routing for registration. Both Mods use it, so the
// capability's dynamic type is the same whichever process published it.
func Capability(service Routing) Routing { return capability{inner: service} }

// OwnerCapabilities is what the owning Mod registers: the interface every
// consumer looks up, plus the owner-only name the Server looks up.
//
// Returned together so the two cannot be published apart. A process that
// registered the first and not the second would serve requests it cannot
// answer locally; one that registered the second and not the first would own a
// service nothing can find.
func OwnerCapabilities(service Routing) []mods.Capability {
	wrapped := Capability(service)
	return []mods.Capability{
		{Name: CapabilityName, Value: wrapped},
		{Name: LocalCapabilityName, Value: wrapped},
	}
}

// --- capability name ---

// CapabilityName is the registry key both Mods publish under.
//
// It is declared here, from the interface's marker, so the name and the
// transport that depends on it are one fact. A repository that also keeps a
// central table of capability names should assert equality against this
// constant rather than repeat the string — two literals of the same name is
// how a Mod ends up ordered by one and looked up by the other.
const CapabilityName app.ModName = "service.global"

// LocalCapabilityName is published ONLY by the owning Mod, and it is how a
// process knows it owns this service.
//
// The alternative was to look up CapabilityName and ask whether the value is a
// *BusClient. That does not work, and finding out why is worth recording: the
// capability is deliberately wrapped so its dynamic type satisfies the
// interface and nothing else, which is exactly what defeats the assertion. The
// first version of this generator shipped that check, and the unit test for it
// passed only because it registered an unwrapped client — not what a Mod does.
//
// Asking "is the local implementation published here" is also the question
// that was actually meant. Type-sniffing for one particular remote
// implementation is a proxy for it, and a proxy that a wrapper, a test double
// or a future in-process forwarder each break differently.
const LocalCapabilityName app.ModName = "service.global.local"

// --- server ---

// Server is the app.Service for a process that runs Routing on its own.
//
// Mod and Service are different concepts, not alternatives, and the generated
// split reflects that:
//
//	Mod:     Init(cfg) / Provide(registry) / Start() / Stop()
//	         PUTS capabilities into the registry. A process has many.
//	Service: Init(registry) / Serve(ctx) / Shutdown(ctx)
//	         TAKES capabilities out and then blocks. A process has exactly one.
//
// The app runs every Mod's Init, Provide and Start, and only then the
// Service's Init and Serve — so a Mod cannot block and a Service cannot be
// looked up by another process. A service that owns its own process needs
// both.
type Server struct {
	service Routing
	bus     bus.IBus
}

// NewServer returns this service's app.Service.
func NewServer() *Server { return &Server{} }

// Name implements app.Service.
func (s *Server) Name() app.ServiceName { return app.ServiceName(ServiceType) }

// Service returns the local implementation, for the run hook.
func (s *Server) Service() Routing { return s.service }

// Init takes what this process needs out of the registry and publishes the
// handlers.
//
// The handlers are registered HERE rather than in the Mod, and that is the
// decision that makes this process the owner: a Mod that registered them would
// publish this service's handlers in any process that happened to load it.
//
// It also refuses to run on a bus client. A process that serves Routing
// over the bus while holding only a client to Routing would forward every
// request to itself, and it would look like it was working until the first
// call.
func (s *Server) Init(r *app.Registry) error {
	service, ok := app.Lookup[Routing](r, LocalCapabilityName)
	if !ok || service == nil {
		if _, remote := app.Lookup[Routing](r, CapabilityName); remote {
			return fmt.Errorf("global server: %q is published but %q is not, so this "+
				"process holds a client to Routing rather than the implementation — it would "+
				"forward every request to itself. Use global.NewMod() here and "+
				"global.NewClientMod() in the processes that call it",
				CapabilityName, LocalCapabilityName)
		}
		return fmt.Errorf("global server: capability %q not found; add global.NewMod()",
			LocalCapabilityName)
	}
	busClient, ok := app.Lookup[bus.IBus](r, mods.ModBus)
	if !ok || busClient == nil {
		return fmt.Errorf("global server: capability %q not found; a process that serves "+
			"Routing needs a bus", mods.ModBus)
	}
	s.service, s.bus = service, busClient
	if err := RegisterHandlers(busClient, service); err != nil {
		return fmt.Errorf("global server: %w", err)
	}
	slog.Info("global server: handlers registered", "methods", len(Methods))
	return nil
}

// Serve blocks until the process is shutting down, running whatever periodic
// work this service has.
//
// The work itself is NOT generated: it calls run, which the author writes in a
// hand-written file. That is deliberate on both counts.
//
// It is here rather than in a Mod because every Mod in this design starts no
// goroutine — "how often does this deployment sweep" is a deployment decision,
// and a loop a Mod starts silently is a loop nobody can see failing. Serve has
// a context, has shutdown semantics, and its failure is the process's failure.
//
// And run is required even for a service with nothing periodic to do, rather
// than defaulted to a blocking no-op. Writing
//
//	func (s *Server) run(ctx context.Context) error { <-ctx.Done(); return nil }
//
// states "nothing periodic" in three lines. A generated default would answer
// the question by not asking it.
func (s *Server) Serve(ctx context.Context) error { return s.run(ctx) }

// Shutdown implements app.Service.
//
// Nothing is drained here: every operation this service exposes is
// synchronous, and the stores belong to the Mod that built them. A service
// that needs to drain should do it at the end of run, where the context that
// asked it to stop is in scope.
func (s *Server) Shutdown(context.Context) error { return nil }

var _ app.Service = (*Server)(nil)

// --- client mod ---

// ClientMod publishes a REMOTE Routing capability, for the processes that
// call this service without owning it.
//
// It registers the same capability name and the same interface type the owning
// Mod does, which is the whole point: business logic looks up
// app.Lookup[Routing] and is identical whether the service runs beside it or
// in another process. Choosing between the two Mods is the deployment
// decision, made once in a process's wiring, and no consumer sees it.
//
// They are mutually exclusive by construction: both publish CapabilityName, so
// the registry refuses the second. A process cannot end up holding both a
// local service and a client to itself with the winner decided by registration
// order.
type ClientMod struct {
	options []servicerpc.Option

	serviceType string
	timeout     time.Duration
	client      *BusClient
}

// NewClientMod returns a client Mod.
//
// options are passed to servicerpc: a deployment that needs a particular
// transport supplies it here, because that is a property of how this
// deployment routes rather than of the service.
func NewClientMod(options ...servicerpc.Option) *ClientMod {
	return &ClientMod{options: append([]servicerpc.Option(nil), options...)}
}

// Name implements app.Mod.
func (m *ClientMod) Name() app.ModName { return CapabilityName }

// DependsOn implements app.ModDependencyProvider.
func (m *ClientMod) DependsOn() []app.ModName { return []app.ModName{mods.ModBus} }

// Init reads configuration.
//
//	global:
//	  service_type: global   # optional, defaults to ServiceType
//	  call_timeout: 3s                 # optional, defaults to DefaultCallTimeout
//
// It reads no key prefix and no store settings, because a client has no store.
// A process that only calls this service therefore cannot be misconfigured
// with a prefix that disagrees with the owner's — it has no prefix to get
// wrong.
func (m *ClientMod) Init(cfg *viper.Viper) error {
	m.serviceType = cfg.GetString("global.service_type")
	if m.serviceType == "" {
		m.serviceType = ServiceType
	}
	// Read inline rather than through a shared helper, so the generated
	// transport depends on nothing but roost-core and roost-kit and works in
	// any repository.
	//
	// A negative value is refused rather than clamped: a caller that wrote -1
	// meant something, and silently reading it as the default hides the
	// mistake.
	m.timeout = DefaultCallTimeout
	if cfg.IsSet("global.call_timeout") {
		timeout := cfg.GetDuration("global.call_timeout")
		if timeout < 0 {
			return fmt.Errorf("global client mod: global.call_timeout must not be "+
				"negative, got %s", timeout)
		}
		if timeout > 0 {
			m.timeout = timeout
		}
	}
	return nil
}

// Provide builds the client and registers it.
func (m *ClientMod) Provide(r *app.Registry) error {
	busClient, ok := app.Lookup[bus.IBus](r, mods.ModBus)
	if !ok || busClient == nil {
		return fmt.Errorf("global client mod: capability %q not found; a process that calls "+
			"Routing needs a bus", mods.ModBus)
	}
	client, err := NewBusClient(busClient, m.serviceType, m.timeout, m.options...)
	if err != nil {
		return fmt.Errorf("global client mod: %w", err)
	}
	m.client = client
	// Registered through Capability, so the dynamic type satisfies Routing
	// and nothing else. A consumer that asserted on *BusClient would break in
	// the process that owns this service.
	return mods.RegisterAll(r, mods.Capability{Name: m.Name(), Value: Capability(client)})
}

// Start implements app.Mod. Nothing to start: the client holds no goroutine
// and the bus's lifecycle belongs to the bus Mod.
func (m *ClientMod) Start() error { return nil }

// Stop implements app.Mod. Nothing to stop, for the same reason.
func (m *ClientMod) Stop() {}

var _ app.Mod = (*ClientMod)(nil)

var (
	_ Routing = (*BusClient)(nil)
	_ Routing = capability{}
)
