// Code generated by roost servicerpc. DO NOT EDIT.
//
// Generated from the Messaging interface in this package. The interface is
// the single source of truth: the wire types, the handler table and the client
// are all derived from it, so a method added to the interface cannot be
// forgotten in the transport — the failure this generator exists to make
// impossible rather than merely detectable.
//
// Regenerate with:
//
//	go run github.com/tjbdwanghaibo/roost-codegen/cmd/servicerpc -dir .

package chat

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/spf13/viper"
	"github.com/tjbdwanghaibo/roost-core/app"
	"github.com/tjbdwanghaibo/roost-core/bus"
	"github.com/tjbdwanghaibo/roost-kit/mods"
	"github.com/tjbdwanghaibo/roost-kit/servicerpc"
)

// ServiceType is the bus service type Messaging answers on. The client and
// the handlers key on it, so it is one constant rather than a string in two
// places.
const ServiceType = "chat"

// The RPC method names, prefixed with the service type so a bus subject is
// unambiguous when several services register handlers on one connection.
const (
	MethodPublish       = "chat.Publish"
	MethodPublishSystem = "chat.PublishSystem"
	MethodHistory       = "chat.History"
	MethodConversation  = "chat.Conversation"
	MethodScrollback    = "chat.Scrollback"
)

// Methods is every method on Messaging, in interface order.
//
// RegisterHandlers iterates it, so a method with no handler fails at startup
// with a name rather than at the first call from another process.
var Methods = []string{
	MethodPublish,
	MethodPublishSystem,
	MethodHistory,
	MethodConversation,
	MethodScrollback,
}

// rpcStatus is the envelope every response embeds.
//
// A business failure travels inside the envelope with this package's error
// code; a bus error means the call did not happen. A caller retrying the
// second and not the first is the difference between recovering and
// double-applying, which is why the two are never the same channel.
type rpcStatus struct {
	Code   int32  `json:"code"`
	Reason string `json:"reason,omitempty"`
}

// StatusCode implements servicerpc.ResponseStatusProvider. The methods are
// exported even though the type is not, which is what the assertion in
// servicerpc.CheckResponse needs.
func (s rpcStatus) StatusCode() int32 { return s.Code }

// StatusReason implements servicerpc.ResponseStatusProvider.
func (s rpcStatus) StatusReason() string { return s.Reason }

// statusOf renders an error using this package's Error, so a code that reaches
// a client is the same code a local caller reads off the error.
func statusOf(err error) rpcStatus {
	code, reason := Error(err)
	return rpcStatus{Code: code, Reason: reason}
}

// --- wire types ---

// rpcPublishRequest is the Publish request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcPublishRequest struct {
	From Sender         `json:"from"`
	Req  PublishRequest `json:"req"`
}

// rpcPublishResponse is the Publish response on the wire.
type rpcPublishResponse struct {
	rpcStatus
	Message Message `json:"message"`
}

// rpcPublishSystemRequest is the PublishSystem request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcPublishSystemRequest struct {
	Req SystemPublishRequest `json:"req"`
}

// rpcPublishSystemResponse is the PublishSystem response on the wire.
type rpcPublishSystemResponse struct {
	rpcStatus
	Message Message `json:"message"`
}

// rpcHistoryRequest is the History request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcHistoryRequest struct {
	Viewer Sender       `json:"viewer"`
	Query  HistoryQuery `json:"query"`
}

// rpcHistoryResponse is the History response on the wire.
type rpcHistoryResponse struct {
	rpcStatus
	Page Page `json:"page"`
}

// rpcConversationRequest is the Conversation request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcConversationRequest struct {
	Viewer   Sender `json:"viewer"`
	Peer     int64  `json:"peer"`
	AfterSeq uint64 `json:"after_seq"`
	Limit    int    `json:"limit"`
}

// rpcConversationResponse is the Conversation response on the wire.
type rpcConversationResponse struct {
	rpcStatus
	Page Page `json:"page"`
}

// rpcScrollbackRequest is the Scrollback request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcScrollbackRequest struct {
	Viewer    Sender `json:"viewer"`
	Peer      int64  `json:"peer"`
	BeforeSeq uint64 `json:"before_seq"`
	Limit     int    `json:"limit"`
}

// rpcScrollbackResponse is the Scrollback response on the wire.
type rpcScrollbackResponse struct {
	rpcStatus
	Page Page `json:"page"`
}

// --- server ---

// RegisterHandlers publishes Messaging on a bus.
//
// It is called by the process that OWNS the service. The handlers decode and
// call the local implementation and contain no logic of their own: a check
// that lived here rather than in the service would apply only to remote
// callers, and a local caller would bypass it.
func RegisterHandlers(b bus.IBus, service Messaging) error {
	if b == nil {
		return fmt.Errorf("chat: bus is nil")
	}
	if service == nil {
		return fmt.Errorf("chat: service is nil")
	}
	handlers := map[string]bus.RpcHandlerFunc{
		MethodPublish: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcPublishRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcPublishResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			message, err := service.Publish(ctx.Context(), wire.From, wire.Req)
			return rpcPublishResponse{rpcStatus: statusOf(err), Message: message}, nil
		},
		MethodPublishSystem: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcPublishSystemRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcPublishSystemResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			message, err := service.PublishSystem(ctx.Context(), wire.Req)
			return rpcPublishSystemResponse{rpcStatus: statusOf(err), Message: message}, nil
		},
		MethodHistory: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcHistoryRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcHistoryResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			page, err := service.History(ctx.Context(), wire.Viewer, wire.Query)
			return rpcHistoryResponse{rpcStatus: statusOf(err), Page: page}, nil
		},
		MethodConversation: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcConversationRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcConversationResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			page, err := service.Conversation(ctx.Context(), wire.Viewer, wire.Peer, wire.AfterSeq, wire.Limit)
			return rpcConversationResponse{rpcStatus: statusOf(err), Page: page}, nil
		},
		MethodScrollback: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcScrollbackRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcScrollbackResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			page, err := service.Scrollback(ctx.Context(), wire.Viewer, wire.Peer, wire.BeforeSeq, wire.Limit)
			return rpcScrollbackResponse{rpcStatus: statusOf(err), Page: page}, nil
		},
	}
	// Registered against Methods rather than by ranging the map, so a method
	// the interface declares and the table misses fails HERE, with a name.
	for _, method := range Methods {
		handler, ok := handlers[method]
		if !ok {
			return fmt.Errorf("chat: no handler for %s", method)
		}
		if err := b.HandleRpc(method, handler); err != nil {
			return fmt.Errorf("chat: register %s: %w", method, err)
		}
	}
	if len(handlers) != len(Methods) {
		return fmt.Errorf("chat: %d handlers for %d methods", len(handlers), len(Methods))
	}
	return nil
}

// --- client ---

// DefaultCallTimeout bounds one RPC. A call with no timeout is a goroutine
// waiting on a process that may never answer.
const DefaultCallTimeout = 3 * time.Second

// BusClient is Messaging over a bus, for the processes that do not own this
// service.
//
// Its method signatures are the interface's, identity included: a caller still
// has to say whose identity it is, and the wire types are this type's
// implementation detail.
type BusClient struct {
	rpc *servicerpc.BusClient
}

// NewBusClient builds a client. serviceType empty means ServiceType; timeout
// non-positive means DefaultCallTimeout.
func NewBusClient(b bus.IBus, serviceType string, timeout time.Duration, opts ...servicerpc.Option) (*BusClient, error) {
	if b == nil {
		return nil, fmt.Errorf("chat: bus is nil")
	}
	if serviceType == "" {
		serviceType = ServiceType
	}
	if timeout <= 0 {
		timeout = DefaultCallTimeout
	}
	return &BusClient{rpc: servicerpc.NewBusClient(b, serviceType, timeout, opts...)}, nil
}

func (c *BusClient) call(ctx context.Context, method string, req any, resp any) error {
	if c == nil || c.rpc == nil {
		return fmt.Errorf("chat: client is not configured")
	}
	return c.rpc.CallChecked(ctx, 0, method, req, resp, "chat call failed")
}

// Publish appends a player's message. The sender is an argument, not a
// request field, so "the caller is the sender" is not a check that can be
// switched off.
// Publish implements Messaging.
func (c *BusClient) Publish(ctx context.Context, from Sender, req PublishRequest) (Message, error) {
	var resp rpcPublishResponse
	err := c.call(ctx, MethodPublish, rpcPublishRequest{
		From: from,
		Req:  req,
	}, &resp)
	return resp.Message, err
}

// PublishSystem appends a message from the game itself. The request
// carries no proof of anything; the grant is minted at the owner from
// transport identity, and its absence is a refusal.
// PublishSystem implements Messaging.
func (c *BusClient) PublishSystem(ctx context.Context, req SystemPublishRequest) (Message, error) {
	var resp rpcPublishSystemResponse
	err := c.call(ctx, MethodPublishSystem, rpcPublishSystemRequest{
		Req: req,
	}, &resp)
	return resp.Message, err
}

// History pages a channel the viewer may read.
// History implements Messaging.
func (c *BusClient) History(ctx context.Context, viewer Sender, query HistoryQuery) (Page, error) {
	var resp rpcHistoryResponse
	err := c.call(ctx, MethodHistory, rpcHistoryRequest{
		Viewer: viewer,
		Query:  query,
	}, &resp)
	return resp.Page, err
}

// Conversation pages the 1:1 conversation between viewer and peer,
// forwards from a reconnect cursor.
// Conversation implements Messaging.
func (c *BusClient) Conversation(ctx context.Context, viewer Sender, peer int64, afterSeq uint64, limit int) (Page, error) {
	var resp rpcConversationResponse
	err := c.call(ctx, MethodConversation, rpcConversationRequest{
		Viewer:   viewer,
		Peer:     peer,
		AfterSeq: afterSeq,
		Limit:    limit,
	}, &resp)
	return resp.Page, err
}

// Scrollback pages the same conversation backwards, for a client
// scrolling up.
// Scrollback implements Messaging.
func (c *BusClient) Scrollback(ctx context.Context, viewer Sender, peer int64, beforeSeq uint64, limit int) (Page, error) {
	var resp rpcScrollbackResponse
	err := c.call(ctx, MethodScrollback, rpcScrollbackRequest{
		Viewer:    viewer,
		Peer:      peer,
		BeforeSeq: beforeSeq,
		Limit:     limit,
	}, &resp)
	return resp.Page, err
}

// --- capability ---

// capability is what a Mod puts in the registry.
//
// It exists because converting to the interface at the registration call site
// does not do what it looks like it does: `Value: Messaging(x)` stores an any
// whose dynamic type is still x's — Go does not box an interface inside an
// interface — so an assertion on the concrete type succeeds anyway. Wrapping
// the interface in a struct makes the dynamic type this wrapper, which
// satisfies Messaging and nothing else.
//
// The consequence is the one that matters: a consumer cannot bind to the local
// implementation and then break on the day this service moves into its own
// process.
//
// It forwards each method explicitly rather than embedding the interface, and
// that is not style. Embedding names the field after the type, so an interface
// with a method of its own name — Rank.Rank, Match.Match — would have the
// field shadow the method and the wrapper would not satisfy the interface at
// all. The second service this generator ran against had exactly that shape.
type capability struct{ inner Messaging }

func (c capability) Publish(ctx context.Context, from Sender, req PublishRequest) (Message, error) {
	return c.inner.Publish(ctx, from, req)
}

func (c capability) PublishSystem(ctx context.Context, req SystemPublishRequest) (Message, error) {
	return c.inner.PublishSystem(ctx, req)
}

func (c capability) History(ctx context.Context, viewer Sender, query HistoryQuery) (Page, error) {
	return c.inner.History(ctx, viewer, query)
}

func (c capability) Conversation(ctx context.Context, viewer Sender, peer int64, afterSeq uint64, limit int) (Page, error) {
	return c.inner.Conversation(ctx, viewer, peer, afterSeq, limit)
}

func (c capability) Scrollback(ctx context.Context, viewer Sender, peer int64, beforeSeq uint64, limit int) (Page, error) {
	return c.inner.Scrollback(ctx, viewer, peer, beforeSeq, limit)
}

// Capability wraps a Messaging for registration. Both Mods use it, so the
// capability's dynamic type is the same whichever process published it.
func Capability(service Messaging) Messaging { return capability{inner: service} }

// OwnerCapabilities is what the owning Mod registers: the interface every
// consumer looks up, plus the owner-only name the Server looks up.
//
// Returned together so the two cannot be published apart. A process that
// registered the first and not the second would serve requests it cannot
// answer locally; one that registered the second and not the first would own a
// service nothing can find.
//
// The two hold DIFFERENT values, and the asymmetry is the point:
//
//   - CapabilityName holds the wrapper, so a consumer cannot bind to the
//     implementation type and then break on the day this service moves out.
//     This is the name every consumer uses.
//   - LocalCapabilityName holds the implementation ITSELF, unwrapped. It is
//     the owning process's handle on its own service, and the Server's run
//     hook needs it: the periodic work a service owns — sweeping expired
//     entries, retrying a failed delivery, pruning retained messages — is
//     deliberately NOT on the cross-process interface, so the hook has to
//     reach the concrete type to call it.
//
// Registering the wrapper under both names is what the first version did, and
// it made every run hook that reaches an owner-only method fail: four services
// returned an error from Serve and could not start, and one asserted lazily
// inside a ticker and panicked thirty seconds in. Nothing caught it because
// nothing called Serve — only Init, which is the half that worked.
//
// This does not weaken the consumer guarantee. LocalCapabilityName exists only
// in the owning process; a consumer that looked it up to get the concrete type
// would find nothing at all in a split deployment, which fails loudly at
// lookup rather than quietly at the type assertion.
func OwnerCapabilities(service Messaging) []mods.Capability {
	return []mods.Capability{
		{Name: CapabilityName, Value: Capability(service)},
		{Name: LocalCapabilityName, Value: service},
	}
}

// --- capability name ---

// CapabilityName is the registry key both Mods publish under.
//
// It is declared here, from the interface's marker, so the name and the
// transport that depends on it are one fact. A repository that also keeps a
// central table of capability names should assert equality against this
// constant rather than repeat the string — two literals of the same name is
// how a Mod ends up ordered by one and looked up by the other.
const CapabilityName app.ModName = "service.chat"

// LocalCapabilityName is published ONLY by the owning Mod, and it is how a
// process knows it owns this service.
//
// The alternative was to look up CapabilityName and ask whether the value is a
// *BusClient. That does not work, and finding out why is worth recording: the
// capability is deliberately wrapped so its dynamic type satisfies the
// interface and nothing else, which is exactly what defeats the assertion. The
// first version of this generator shipped that check, and the unit test for it
// passed only because it registered an unwrapped client — not what a Mod does.
//
// Asking "is the local implementation published here" is also the question
// that was actually meant. Type-sniffing for one particular remote
// implementation is a proxy for it, and a proxy that a wrapper, a test double
// or a future in-process forwarder each break differently.
const LocalCapabilityName app.ModName = "service.chat.local"

// --- server ---

// Server is the app.Service for a process that runs Messaging on its own.
//
// Mod and Service are different concepts, not alternatives, and the generated
// split reflects that:
//
//	Mod:     Init(cfg) / Provide(registry) / Start() / Stop()
//	         PUTS capabilities into the registry. A process has many.
//	Service: Init(registry) / Serve(ctx) / Shutdown(ctx)
//	         TAKES capabilities out and then blocks. A process has exactly one.
//
// The app runs every Mod's Init, Provide and Start, and only then the
// Service's Init and Serve — so a Mod cannot block and a Service cannot be
// looked up by another process. A service that owns its own process needs
// both.
type Server struct {
	service Messaging
	bus     bus.IBus
}

// NewServer returns this service's app.Service.
func NewServer() *Server { return &Server{} }

// Name implements app.Service.
func (s *Server) Name() app.ServiceName { return app.ServiceName(ServiceType) }

// Service returns the local implementation, for the run hook.
func (s *Server) Service() Messaging { return s.service }

// Init takes what this process needs out of the registry and publishes the
// handlers.
//
// The handlers are registered HERE rather than in the Mod, and that is the
// decision that makes this process the owner: a Mod that registered them would
// publish this service's handlers in any process that happened to load it.
//
// It also refuses to run on a bus client. A process that serves Messaging
// over the bus while holding only a client to Messaging would forward every
// request to itself, and it would look like it was working until the first
// call.
func (s *Server) Init(r *app.Registry) error {
	service, ok := app.Lookup[Messaging](r, LocalCapabilityName)
	if !ok || service == nil {
		if _, remote := app.Lookup[Messaging](r, CapabilityName); remote {
			return fmt.Errorf("chat server: %q is published but %q is not, so this "+
				"process holds a client to Messaging rather than the implementation — it would "+
				"forward every request to itself. Use chat.NewMod() here and "+
				"chat.NewClientMod() in the processes that call it",
				CapabilityName, LocalCapabilityName)
		}
		return fmt.Errorf("chat server: capability %q not found; add chat.NewMod()",
			LocalCapabilityName)
	}
	busClient, ok := app.Lookup[bus.IBus](r, mods.ModBus)
	if !ok || busClient == nil {
		return fmt.Errorf("chat server: capability %q not found; a process that serves "+
			"Messaging needs a bus", mods.ModBus)
	}
	s.service, s.bus = service, busClient
	if err := RegisterHandlers(busClient, service); err != nil {
		return fmt.Errorf("chat server: %w", err)
	}
	slog.Info("chat server: handlers registered", "methods", len(Methods))
	return nil
}

// Serve blocks until the process is shutting down, running whatever periodic
// work this service has.
//
// The work itself is NOT generated: it calls run, which the author writes in a
// hand-written file. That is deliberate on both counts.
//
// It is here rather than in a Mod because every Mod in this design starts no
// goroutine — "how often does this deployment sweep" is a deployment decision,
// and a loop a Mod starts silently is a loop nobody can see failing. Serve has
// a context, has shutdown semantics, and its failure is the process's failure.
//
// And run is required even for a service with nothing periodic to do, rather
// than defaulted to a blocking no-op. Writing
//
//	func (s *Server) run(ctx context.Context) error { <-ctx.Done(); return nil }
//
// states "nothing periodic" in three lines. A generated default would answer
// the question by not asking it.
func (s *Server) Serve(ctx context.Context) error { return s.run(ctx) }

// Shutdown implements app.Service.
//
// Nothing is drained here: every operation this service exposes is
// synchronous, and the stores belong to the Mod that built them. A service
// that needs to drain should do it at the end of run, where the context that
// asked it to stop is in scope.
func (s *Server) Shutdown(context.Context) error { return nil }

var _ app.Service = (*Server)(nil)

// --- client mod ---

// ClientMod publishes a REMOTE Messaging capability, for the processes that
// call this service without owning it.
//
// It registers the same capability name and the same interface type the owning
// Mod does, which is the whole point: business logic looks up
// app.Lookup[Messaging] and is identical whether the service runs beside it or
// in another process. Choosing between the two Mods is the deployment
// decision, made once in a process's wiring, and no consumer sees it.
//
// They are mutually exclusive by construction: both publish CapabilityName, so
// the registry refuses the second. A process cannot end up holding both a
// local service and a client to itself with the winner decided by registration
// order.
type ClientMod struct {
	options []servicerpc.Option

	serviceType string
	timeout     time.Duration
	client      *BusClient
}

// NewClientMod returns a client Mod.
//
// options are passed to servicerpc: a deployment that needs a particular
// transport supplies it here, because that is a property of how this
// deployment routes rather than of the service.
func NewClientMod(options ...servicerpc.Option) *ClientMod {
	return &ClientMod{options: append([]servicerpc.Option(nil), options...)}
}

// Name implements app.Mod.
func (m *ClientMod) Name() app.ModName { return CapabilityName }

// DependsOn implements app.ModDependencyProvider.
//
// It names the Mod that publishes the bus — kit's NATS mod — not the bus
// capability. app resolves dependencies by Mod NAME, so a ClientMod that
// depended on mods.ModBus ("bus", a capability nobody is named after) could
// never be assembled in a real process: "unknown mod dependency \"bus\"".
// That shipped in every generated client until a generated game template
// tried to start (roost-codegen U-0024).
func (m *ClientMod) DependsOn() []app.ModName { return []app.ModName{mods.ModNats} }

// Init reads configuration.
//
//	chat:
//	  service_type: chat   # optional, defaults to ServiceType
//	  call_timeout: 3s                 # optional, defaults to DefaultCallTimeout
//
// It reads no key prefix and no store settings, because a client has no store.
// A process that only calls this service therefore cannot be misconfigured
// with a prefix that disagrees with the owner's — it has no prefix to get
// wrong.
func (m *ClientMod) Init(cfg *viper.Viper) error {
	m.serviceType = cfg.GetString("chat.service_type")
	if m.serviceType == "" {
		m.serviceType = ServiceType
	}
	// Read inline rather than through a shared helper, so the generated
	// transport depends on nothing but roost-core and roost-kit and works in
	// any repository.
	//
	// A negative value is refused rather than clamped: a caller that wrote -1
	// meant something, and silently reading it as the default hides the
	// mistake.
	m.timeout = DefaultCallTimeout
	if cfg.IsSet("chat.call_timeout") {
		timeout := cfg.GetDuration("chat.call_timeout")
		if timeout < 0 {
			return fmt.Errorf("chat client mod: chat.call_timeout must not be "+
				"negative, got %s", timeout)
		}
		if timeout > 0 {
			m.timeout = timeout
		}
	}
	return nil
}

// Provide builds the client and registers it.
func (m *ClientMod) Provide(r *app.Registry) error {
	busClient, ok := app.Lookup[bus.IBus](r, mods.ModBus)
	if !ok || busClient == nil {
		return fmt.Errorf("chat client mod: capability %q not found; a process that calls "+
			"Messaging needs a bus", mods.ModBus)
	}
	client, err := NewBusClient(busClient, m.serviceType, m.timeout, m.options...)
	if err != nil {
		return fmt.Errorf("chat client mod: %w", err)
	}
	m.client = client
	// Registered through Capability, so the dynamic type satisfies Messaging
	// and nothing else. A consumer that asserted on *BusClient would break in
	// the process that owns this service.
	return mods.RegisterAll(r, mods.Capability{Name: m.Name(), Value: Capability(client)})
}

// Start implements app.Mod. Nothing to start: the client holds no goroutine
// and the bus's lifecycle belongs to the bus Mod.
func (m *ClientMod) Start() error { return nil }

// Stop implements app.Mod. Nothing to stop, for the same reason.
func (m *ClientMod) Stop() {}

var _ app.Mod = (*ClientMod)(nil)

var (
	_ Messaging = (*BusClient)(nil)
	_ Messaging = capability{}
)
