// Code generated by roost servicerpc. DO NOT EDIT.
//
// Generated from the Matchmaker interface in this package. The interface is
// the single source of truth: the wire types, the handler table and the client
// are all derived from it, so a method added to the interface cannot be
// forgotten in the transport — the failure this generator exists to make
// impossible rather than merely detectable.
//
// Regenerate with:
//
//	go run github.com/tjbdwanghaibo/roost-codegen/cmd/servicerpc -dir .

package match

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/spf13/viper"
	"github.com/tjbdwanghaibo/roost-core/app"
	"github.com/tjbdwanghaibo/roost-core/bus"
	"github.com/tjbdwanghaibo/roost-kit/mods"
	"github.com/tjbdwanghaibo/roost-kit/servicerpc"
)

// ServiceType is the bus service type Matchmaker answers on. The client and
// the handlers key on it, so it is one constant rather than a string in two
// places.
const ServiceType = "match"

// The RPC method names, prefixed with the service type so a bus subject is
// unambiguous when several services register handlers on one connection.
const (
	MethodEnqueue     = "match.Enqueue"
	MethodCancel      = "match.Cancel"
	MethodTicket      = "match.Ticket"
	MethodCandidates  = "match.Candidates"
	MethodCommit      = "match.Commit"
	MethodMatch       = "match.Match"
	MethodQueueLength = "match.QueueLength"
)

// Methods is every method on Matchmaker, in interface order.
//
// RegisterHandlers iterates it, so a method with no handler fails at startup
// with a name rather than at the first call from another process.
var Methods = []string{
	MethodEnqueue,
	MethodCancel,
	MethodTicket,
	MethodCandidates,
	MethodCommit,
	MethodMatch,
	MethodQueueLength,
}

// rpcStatus is the envelope every response embeds.
//
// A business failure travels inside the envelope with this package's error
// code; a bus error means the call did not happen. A caller retrying the
// second and not the first is the difference between recovering and
// double-applying, which is why the two are never the same channel.
type rpcStatus struct {
	Code   int32  `json:"code"`
	Reason string `json:"reason,omitempty"`
}

// StatusCode implements servicerpc.ResponseStatusProvider. The methods are
// exported even though the type is not, which is what the assertion in
// servicerpc.CheckResponse needs.
func (s rpcStatus) StatusCode() int32 { return s.Code }

// StatusReason implements servicerpc.ResponseStatusProvider.
func (s rpcStatus) StatusReason() string { return s.Reason }

// statusOf renders an error using this package's Error, so a code that reaches
// a client is the same code a local caller reads off the error.
func statusOf(err error) rpcStatus {
	code, reason := Error(err)
	return rpcStatus{Code: code, Reason: reason}
}

// --- wire types ---

// rpcEnqueueRequest is the Enqueue request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcEnqueueRequest struct {
	Queue     Queue   `json:"queue"`
	Subject   Subject `json:"subject"`
	RequestID string  `json:"request_id"`
}

// rpcEnqueueResponse is the Enqueue response on the wire.
type rpcEnqueueResponse struct {
	rpcStatus
	Ticket Ticket `json:"ticket"`
}

// rpcCancelRequest is the Cancel request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcCancelRequest struct {
	Queue    Queue   `json:"queue"`
	TicketID string  `json:"ticket_id"`
	Subject  Subject `json:"subject"`
}

// rpcCancelResponse is the Cancel response on the wire.
type rpcCancelResponse struct {
	rpcStatus
	Ticket Ticket `json:"ticket"`
}

// rpcTicketRequest is the Ticket request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcTicketRequest struct {
	Queue    Queue   `json:"queue"`
	TicketID string  `json:"ticket_id"`
	Subject  Subject `json:"subject"`
}

// rpcTicketResponse is the Ticket response on the wire.
type rpcTicketResponse struct {
	rpcStatus
	Ticket Ticket `json:"ticket"`
	Found  bool   `json:"found"`
}

// rpcCandidatesRequest is the Candidates request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcCandidatesRequest struct {
	Queue Queue `json:"queue"`
	Limit int   `json:"limit"`
}

// rpcCandidatesResponse is the Candidates response on the wire.
type rpcCandidatesResponse struct {
	rpcStatus
	Tickets []Ticket `json:"tickets"`
}

// rpcCommitRequest is the Commit request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcCommitRequest struct {
	Queue     Queue    `json:"queue"`
	TicketIDs []string `json:"ticket_i_ds"`
}

// rpcCommitResponse is the Commit response on the wire.
type rpcCommitResponse struct {
	rpcStatus
	Match Match `json:"match"`
}

// rpcMatchRequest is the Match request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcMatchRequest struct {
	Queue   Queue  `json:"queue"`
	MatchID string `json:"match_id"`
}

// rpcMatchResponse is the Match response on the wire.
type rpcMatchResponse struct {
	rpcStatus
	Match Match `json:"match"`
	Found bool  `json:"found"`
}

// rpcQueueLengthRequest is the QueueLength request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcQueueLengthRequest struct {
	Queue Queue `json:"queue"`
}

// rpcQueueLengthResponse is the QueueLength response on the wire.
type rpcQueueLengthResponse struct {
	rpcStatus
	Length int `json:"length"`
}

// --- server ---

// RegisterHandlers publishes Matchmaker on a bus.
//
// It is called by the process that OWNS the service. The handlers decode and
// call the local implementation and contain no logic of their own: a check
// that lived here rather than in the service would apply only to remote
// callers, and a local caller would bypass it.
func RegisterHandlers(b bus.IBus, service Matchmaker) error {
	if b == nil {
		return fmt.Errorf("match: bus is nil")
	}
	if service == nil {
		return fmt.Errorf("match: service is nil")
	}
	handlers := map[string]bus.RpcHandlerFunc{
		MethodEnqueue: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcEnqueueRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcEnqueueResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			ticket, err := service.Enqueue(ctx.Context(), wire.Queue, wire.Subject, wire.RequestID)
			return rpcEnqueueResponse{rpcStatus: statusOf(err), Ticket: ticket}, nil
		},
		MethodCancel: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcCancelRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcCancelResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			ticket, err := service.Cancel(ctx.Context(), wire.Queue, wire.TicketID, wire.Subject)
			return rpcCancelResponse{rpcStatus: statusOf(err), Ticket: ticket}, nil
		},
		MethodTicket: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcTicketRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcTicketResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			ticket, found, err := service.Ticket(ctx.Context(), wire.Queue, wire.TicketID, wire.Subject)
			return rpcTicketResponse{rpcStatus: statusOf(err), Ticket: ticket, Found: found}, nil
		},
		MethodCandidates: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcCandidatesRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcCandidatesResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			tickets, err := service.Candidates(ctx.Context(), wire.Queue, wire.Limit)
			return rpcCandidatesResponse{rpcStatus: statusOf(err), Tickets: tickets}, nil
		},
		MethodCommit: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcCommitRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcCommitResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			match, err := service.Commit(ctx.Context(), wire.Queue, wire.TicketIDs)
			return rpcCommitResponse{rpcStatus: statusOf(err), Match: match}, nil
		},
		MethodMatch: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcMatchRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcMatchResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			match, found, err := service.Match(ctx.Context(), wire.Queue, wire.MatchID)
			return rpcMatchResponse{rpcStatus: statusOf(err), Match: match, Found: found}, nil
		},
		MethodQueueLength: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcQueueLengthRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcQueueLengthResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			length, err := service.QueueLength(ctx.Context(), wire.Queue)
			return rpcQueueLengthResponse{rpcStatus: statusOf(err), Length: length}, nil
		},
	}
	// Registered against Methods rather than by ranging the map, so a method
	// the interface declares and the table misses fails HERE, with a name.
	for _, method := range Methods {
		handler, ok := handlers[method]
		if !ok {
			return fmt.Errorf("match: no handler for %s", method)
		}
		if err := b.HandleRpc(method, handler); err != nil {
			return fmt.Errorf("match: register %s: %w", method, err)
		}
	}
	if len(handlers) != len(Methods) {
		return fmt.Errorf("match: %d handlers for %d methods", len(handlers), len(Methods))
	}
	return nil
}

// --- client ---

// DefaultCallTimeout bounds one RPC. A call with no timeout is a goroutine
// waiting on a process that may never answer.
const DefaultCallTimeout = 3 * time.Second

// BusClient is Matchmaker over a bus, for the processes that do not own this
// service.
//
// Its method signatures are the interface's, identity included: a caller still
// has to say whose identity it is, and the wire types are this type's
// implementation detail.
type BusClient struct {
	rpc *servicerpc.BusClient
}

// NewBusClient builds a client. serviceType empty means ServiceType; timeout
// non-positive means DefaultCallTimeout.
func NewBusClient(b bus.IBus, serviceType string, timeout time.Duration, opts ...servicerpc.Option) (*BusClient, error) {
	if b == nil {
		return nil, fmt.Errorf("match: bus is nil")
	}
	if serviceType == "" {
		serviceType = ServiceType
	}
	if timeout <= 0 {
		timeout = DefaultCallTimeout
	}
	// At least one method routes by key, so the picker that reads the key is
	// installed here rather than left to each deployment to remember. A
	// caller's own options come after, so it can still override.
	//
	// This matters for a specific reason: a service whose state is partitioned
	// across instances — a queue kept whole in one key, say — has its
	// throughput bounded by contention on that key, and round-robin routing
	// turns that bound into cross-replica contention. Routing by key makes the
	// contention in-process instead. It is the difference between a design
	// cost and a design defect.
	options := append([]servicerpc.Option{
		servicerpc.WithKeyAffinity(servicerpc.AffinityKeyFromContext),
	}, opts...)
	return &BusClient{rpc: servicerpc.NewBusClient(b, serviceType, timeout, options...)}, nil
}

func (c *BusClient) call(ctx context.Context, method string, req any, resp any) error {
	if c == nil || c.rpc == nil {
		return fmt.Errorf("match: client is not configured")
	}
	return c.rpc.CallChecked(ctx, 0, method, req, resp, "match call failed")
}

// Enqueue adds a subject to a queue. Idempotent per requestID.
//
// Enqueue implements Matchmaker.
func (c *BusClient) Enqueue(ctx context.Context, queue Queue, subject Subject, requestID string) (Ticket, error) {
	// Routed by queue.Key(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, queue.Key())
	var resp rpcEnqueueResponse
	err := c.call(ctx, MethodEnqueue, rpcEnqueueRequest{
		Queue:     queue,
		Subject:   subject,
		RequestID: requestID,
	}, &resp)
	return resp.Ticket, err
}

// Cancel withdraws a ticket. The subject is required, so a caller cannot
// cancel a ticket it does not own — the confirmed defect it answers took
// the ticket id from the client and used it as identity.
//
// Cancel implements Matchmaker.
func (c *BusClient) Cancel(ctx context.Context, queue Queue, ticketID string, subject Subject) (Ticket, error) {
	// Routed by queue.Key(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, queue.Key())
	var resp rpcCancelResponse
	err := c.call(ctx, MethodCancel, rpcCancelRequest{
		Queue:    queue,
		TicketID: ticketID,
		Subject:  subject,
	}, &resp)
	return resp.Ticket, err
}

// Ticket reads one ticket, checking ownership.
//
// Ticket implements Matchmaker.
func (c *BusClient) Ticket(ctx context.Context, queue Queue, ticketID string, subject Subject) (Ticket, bool, error) {
	// Routed by queue.Key(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, queue.Key())
	var resp rpcTicketResponse
	err := c.call(ctx, MethodTicket, rpcTicketRequest{
		Queue:    queue,
		TicketID: ticketID,
		Subject:  subject,
	}, &resp)
	return resp.Ticket, resp.Found, err
}

// Candidates reads a bounded window of waiting tickets, for a caller that
// forms its own groups.
//
// Candidates implements Matchmaker.
func (c *BusClient) Candidates(ctx context.Context, queue Queue, limit int) ([]Ticket, error) {
	// Routed by queue.Key(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, queue.Key())
	var resp rpcCandidatesResponse
	err := c.call(ctx, MethodCandidates, rpcCandidatesRequest{
		Queue: queue,
		Limit: limit,
	}, &resp)
	return resp.Tickets, err
}

// Commit forms a match from tickets in ONE compare-and-set, which is what
// makes the batch atomic — the implementation this replaces wrote it in
// three non-atomic steps and lost whole batches from the queue.
//
// Commit implements Matchmaker.
func (c *BusClient) Commit(ctx context.Context, queue Queue, ticketIDs []string) (Match, error) {
	// Routed by queue.Key(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, queue.Key())
	var resp rpcCommitResponse
	err := c.call(ctx, MethodCommit, rpcCommitRequest{
		Queue:     queue,
		TicketIDs: ticketIDs,
	}, &resp)
	return resp.Match, err
}

// Match reads one match.
//
// Match implements Matchmaker.
func (c *BusClient) Match(ctx context.Context, queue Queue, matchID string) (Match, bool, error) {
	// Routed by queue.Key(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, queue.Key())
	var resp rpcMatchResponse
	err := c.call(ctx, MethodMatch, rpcMatchRequest{
		Queue:   queue,
		MatchID: matchID,
	}, &resp)
	return resp.Match, resp.Found, err
}

// QueueLength reports how many subjects are waiting.
//
// QueueLength implements Matchmaker.
func (c *BusClient) QueueLength(ctx context.Context, queue Queue) (int, error) {
	// Routed by queue.Key(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, queue.Key())
	var resp rpcQueueLengthResponse
	err := c.call(ctx, MethodQueueLength, rpcQueueLengthRequest{
		Queue: queue,
	}, &resp)
	return resp.Length, err
}

// --- capability ---

// capability is what a Mod puts in the registry.
//
// It exists because converting to the interface at the registration call site
// does not do what it looks like it does: `Value: Matchmaker(x)` stores an any
// whose dynamic type is still x's — Go does not box an interface inside an
// interface — so an assertion on the concrete type succeeds anyway. Wrapping
// the interface in a struct makes the dynamic type this wrapper, which
// satisfies Matchmaker and nothing else.
//
// The consequence is the one that matters: a consumer cannot bind to the local
// implementation and then break on the day this service moves into its own
// process.
//
// It forwards each method explicitly rather than embedding the interface, and
// that is not style. Embedding names the field after the type, so an interface
// with a method of its own name — Rank.Rank, Match.Match — would have the
// field shadow the method and the wrapper would not satisfy the interface at
// all. The second service this generator ran against had exactly that shape.
type capability struct{ inner Matchmaker }

func (c capability) Enqueue(ctx context.Context, queue Queue, subject Subject, requestID string) (Ticket, error) {
	return c.inner.Enqueue(ctx, queue, subject, requestID)
}

func (c capability) Cancel(ctx context.Context, queue Queue, ticketID string, subject Subject) (Ticket, error) {
	return c.inner.Cancel(ctx, queue, ticketID, subject)
}

func (c capability) Ticket(ctx context.Context, queue Queue, ticketID string, subject Subject) (Ticket, bool, error) {
	return c.inner.Ticket(ctx, queue, ticketID, subject)
}

func (c capability) Candidates(ctx context.Context, queue Queue, limit int) ([]Ticket, error) {
	return c.inner.Candidates(ctx, queue, limit)
}

func (c capability) Commit(ctx context.Context, queue Queue, ticketIDs []string) (Match, error) {
	return c.inner.Commit(ctx, queue, ticketIDs)
}

func (c capability) Match(ctx context.Context, queue Queue, matchID string) (Match, bool, error) {
	return c.inner.Match(ctx, queue, matchID)
}

func (c capability) QueueLength(ctx context.Context, queue Queue) (int, error) {
	return c.inner.QueueLength(ctx, queue)
}

// Capability wraps a Matchmaker for registration. Both Mods use it, so the
// capability's dynamic type is the same whichever process published it.
func Capability(service Matchmaker) Matchmaker { return capability{inner: service} }

// OwnerCapabilities is what the owning Mod registers: the interface every
// consumer looks up, plus the owner-only name the Server looks up.
//
// Returned together so the two cannot be published apart. A process that
// registered the first and not the second would serve requests it cannot
// answer locally; one that registered the second and not the first would own a
// service nothing can find.
//
// The two hold DIFFERENT values, and the asymmetry is the point:
//
//   - CapabilityName holds the wrapper, so a consumer cannot bind to the
//     implementation type and then break on the day this service moves out.
//     This is the name every consumer uses.
//   - LocalCapabilityName holds the implementation ITSELF, unwrapped. It is
//     the owning process's handle on its own service, and the Server's run
//     hook needs it: the periodic work a service owns — sweeping expired
//     entries, retrying a failed delivery, pruning retained messages — is
//     deliberately NOT on the cross-process interface, so the hook has to
//     reach the concrete type to call it.
//
// Registering the wrapper under both names is what the first version did, and
// it made every run hook that reaches an owner-only method fail: four services
// returned an error from Serve and could not start, and one asserted lazily
// inside a ticker and panicked thirty seconds in. Nothing caught it because
// nothing called Serve — only Init, which is the half that worked.
//
// This does not weaken the consumer guarantee. LocalCapabilityName exists only
// in the owning process; a consumer that looked it up to get the concrete type
// would find nothing at all in a split deployment, which fails loudly at
// lookup rather than quietly at the type assertion.
func OwnerCapabilities(service Matchmaker) []mods.Capability {
	return []mods.Capability{
		{Name: CapabilityName, Value: Capability(service)},
		{Name: LocalCapabilityName, Value: service},
	}
}

// --- capability name ---

// CapabilityName is the registry key both Mods publish under.
//
// It is declared here, from the interface's marker, so the name and the
// transport that depends on it are one fact. A repository that also keeps a
// central table of capability names should assert equality against this
// constant rather than repeat the string — two literals of the same name is
// how a Mod ends up ordered by one and looked up by the other.
const CapabilityName app.ModName = "service.match"

// LocalCapabilityName is published ONLY by the owning Mod, and it is how a
// process knows it owns this service.
//
// The alternative was to look up CapabilityName and ask whether the value is a
// *BusClient. That does not work, and finding out why is worth recording: the
// capability is deliberately wrapped so its dynamic type satisfies the
// interface and nothing else, which is exactly what defeats the assertion. The
// first version of this generator shipped that check, and the unit test for it
// passed only because it registered an unwrapped client — not what a Mod does.
//
// Asking "is the local implementation published here" is also the question
// that was actually meant. Type-sniffing for one particular remote
// implementation is a proxy for it, and a proxy that a wrapper, a test double
// or a future in-process forwarder each break differently.
const LocalCapabilityName app.ModName = "service.match.local"

// --- server ---

// Server is the app.Service for a process that runs Matchmaker on its own.
//
// Mod and Service are different concepts, not alternatives, and the generated
// split reflects that:
//
//	Mod:     Init(cfg) / Provide(registry) / Start() / Stop()
//	         PUTS capabilities into the registry. A process has many.
//	Service: Init(registry) / Serve(ctx) / Shutdown(ctx)
//	         TAKES capabilities out and then blocks. A process has exactly one.
//
// The app runs every Mod's Init, Provide and Start, and only then the
// Service's Init and Serve — so a Mod cannot block and a Service cannot be
// looked up by another process. A service that owns its own process needs
// both.
type Server struct {
	service Matchmaker
	bus     bus.IBus
}

// NewServer returns this service's app.Service.
func NewServer() *Server { return &Server{} }

// Name implements app.Service.
func (s *Server) Name() app.ServiceName { return app.ServiceName(ServiceType) }

// Service returns the local implementation, for the run hook.
func (s *Server) Service() Matchmaker { return s.service }

// Init takes what this process needs out of the registry and publishes the
// handlers.
//
// The handlers are registered HERE rather than in the Mod, and that is the
// decision that makes this process the owner: a Mod that registered them would
// publish this service's handlers in any process that happened to load it.
//
// It also refuses to run on a bus client. A process that serves Matchmaker
// over the bus while holding only a client to Matchmaker would forward every
// request to itself, and it would look like it was working until the first
// call.
func (s *Server) Init(r *app.Registry) error {
	service, ok := app.Lookup[Matchmaker](r, LocalCapabilityName)
	if !ok || service == nil {
		if _, remote := app.Lookup[Matchmaker](r, CapabilityName); remote {
			return fmt.Errorf("match server: %q is published but %q is not, so this "+
				"process holds a client to Matchmaker rather than the implementation — it would "+
				"forward every request to itself. Use match.NewMod() here and "+
				"match.NewClientMod() in the processes that call it",
				CapabilityName, LocalCapabilityName)
		}
		return fmt.Errorf("match server: capability %q not found; add match.NewMod()",
			LocalCapabilityName)
	}
	busClient, ok := app.Lookup[bus.IBus](r, mods.ModBus)
	if !ok || busClient == nil {
		return fmt.Errorf("match server: capability %q not found; a process that serves "+
			"Matchmaker needs a bus", mods.ModBus)
	}
	s.service, s.bus = service, busClient
	if err := RegisterHandlers(busClient, service); err != nil {
		return fmt.Errorf("match server: %w", err)
	}
	slog.Info("match server: handlers registered", "methods", len(Methods))
	return nil
}

// Serve blocks until the process is shutting down, running whatever periodic
// work this service has.
//
// The work itself is NOT generated: it calls run, which the author writes in a
// hand-written file. That is deliberate on both counts.
//
// It is here rather than in a Mod because every Mod in this design starts no
// goroutine — "how often does this deployment sweep" is a deployment decision,
// and a loop a Mod starts silently is a loop nobody can see failing. Serve has
// a context, has shutdown semantics, and its failure is the process's failure.
//
// And run is required even for a service with nothing periodic to do, rather
// than defaulted to a blocking no-op. Writing
//
//	func (s *Server) run(ctx context.Context) error { <-ctx.Done(); return nil }
//
// states "nothing periodic" in three lines. A generated default would answer
// the question by not asking it.
func (s *Server) Serve(ctx context.Context) error { return s.run(ctx) }

// Shutdown implements app.Service.
//
// Nothing is drained here: every operation this service exposes is
// synchronous, and the stores belong to the Mod that built them. A service
// that needs to drain should do it at the end of run, where the context that
// asked it to stop is in scope.
func (s *Server) Shutdown(context.Context) error { return nil }

var _ app.Service = (*Server)(nil)

// --- client mod ---

// ClientMod publishes a REMOTE Matchmaker capability, for the processes that
// call this service without owning it.
//
// It registers the same capability name and the same interface type the owning
// Mod does, which is the whole point: business logic looks up
// app.Lookup[Matchmaker] and is identical whether the service runs beside it or
// in another process. Choosing between the two Mods is the deployment
// decision, made once in a process's wiring, and no consumer sees it.
//
// They are mutually exclusive by construction: both publish CapabilityName, so
// the registry refuses the second. A process cannot end up holding both a
// local service and a client to itself with the winner decided by registration
// order.
type ClientMod struct {
	options []servicerpc.Option

	serviceType string
	timeout     time.Duration
	client      *BusClient
}

// NewClientMod returns a client Mod.
//
// options are passed to servicerpc: a deployment that needs a particular
// transport supplies it here, because that is a property of how this
// deployment routes rather than of the service.
func NewClientMod(options ...servicerpc.Option) *ClientMod {
	return &ClientMod{options: append([]servicerpc.Option(nil), options...)}
}

// Name implements app.Mod.
func (m *ClientMod) Name() app.ModName { return CapabilityName }

// DependsOn implements app.ModDependencyProvider.
func (m *ClientMod) DependsOn() []app.ModName { return []app.ModName{mods.ModBus} }

// Init reads configuration.
//
//	match:
//	  service_type: match   # optional, defaults to ServiceType
//	  call_timeout: 3s                 # optional, defaults to DefaultCallTimeout
//
// It reads no key prefix and no store settings, because a client has no store.
// A process that only calls this service therefore cannot be misconfigured
// with a prefix that disagrees with the owner's — it has no prefix to get
// wrong.
func (m *ClientMod) Init(cfg *viper.Viper) error {
	m.serviceType = cfg.GetString("match.service_type")
	if m.serviceType == "" {
		m.serviceType = ServiceType
	}
	// Read inline rather than through a shared helper, so the generated
	// transport depends on nothing but roost-core and roost-kit and works in
	// any repository.
	//
	// A negative value is refused rather than clamped: a caller that wrote -1
	// meant something, and silently reading it as the default hides the
	// mistake.
	m.timeout = DefaultCallTimeout
	if cfg.IsSet("match.call_timeout") {
		timeout := cfg.GetDuration("match.call_timeout")
		if timeout < 0 {
			return fmt.Errorf("match client mod: match.call_timeout must not be "+
				"negative, got %s", timeout)
		}
		if timeout > 0 {
			m.timeout = timeout
		}
	}
	return nil
}

// Provide builds the client and registers it.
func (m *ClientMod) Provide(r *app.Registry) error {
	busClient, ok := app.Lookup[bus.IBus](r, mods.ModBus)
	if !ok || busClient == nil {
		return fmt.Errorf("match client mod: capability %q not found; a process that calls "+
			"Matchmaker needs a bus", mods.ModBus)
	}
	client, err := NewBusClient(busClient, m.serviceType, m.timeout, m.options...)
	if err != nil {
		return fmt.Errorf("match client mod: %w", err)
	}
	m.client = client
	// Registered through Capability, so the dynamic type satisfies Matchmaker
	// and nothing else. A consumer that asserted on *BusClient would break in
	// the process that owns this service.
	return mods.RegisterAll(r, mods.Capability{Name: m.Name(), Value: Capability(client)})
}

// Start implements app.Mod. Nothing to start: the client holds no goroutine
// and the bus's lifecycle belongs to the bus Mod.
func (m *ClientMod) Start() error { return nil }

// Stop implements app.Mod. Nothing to stop, for the same reason.
func (m *ClientMod) Stop() {}

var _ app.Mod = (*ClientMod)(nil)

var (
	_ Matchmaker = (*BusClient)(nil)
	_ Matchmaker = capability{}
)
