// Code generated by roost servicerpc. DO NOT EDIT.
//
// Generated from the Session interface in this package. The interface is
// the single source of truth: the wire types, the handler table and the client
// are all derived from it, so a method added to the interface cannot be
// forgotten in the transport — the failure this generator exists to make
// impossible rather than merely detectable.
//
// Regenerate with:
//
//	go run github.com/tjbdwanghaibo/roost-codegen/cmd/servicerpc -dir .

package session

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/spf13/viper"
	"github.com/tjbdwanghaibo/roost-core/app"
	"github.com/tjbdwanghaibo/roost-core/bus"
	"github.com/tjbdwanghaibo/roost-kit/mods"
	"github.com/tjbdwanghaibo/roost-kit/servicerpc"
)

// ServiceType is the bus service type Session answers on. The client and
// the handlers key on it, so it is one constant rather than a string in two
// places.
const ServiceType = "session"

// The RPC method names, prefixed with the service type so a bus subject is
// unambiguous when several services register handlers on one connection.
const (
	MethodEnter   = "session.Enter"
	MethodAttach  = "session.Attach"
	MethodFinish  = "session.Finish"
	MethodLeave   = "session.Leave"
	MethodGet     = "session.Get"
	MethodCurrent = "session.Current"
)

// Methods is every method on Session, in interface order.
//
// RegisterHandlers iterates it, so a method with no handler fails at startup
// with a name rather than at the first call from another process.
var Methods = []string{
	MethodEnter,
	MethodAttach,
	MethodFinish,
	MethodLeave,
	MethodGet,
	MethodCurrent,
}

// rpcStatus is the envelope every response embeds.
//
// A business failure travels inside the envelope with this package's error
// code; a bus error means the call did not happen. A caller retrying the
// second and not the first is the difference between recovering and
// double-applying, which is why the two are never the same channel.
type rpcStatus struct {
	Code   int32  `json:"code"`
	Reason string `json:"reason,omitempty"`
}

// StatusCode implements servicerpc.ResponseStatusProvider. The methods are
// exported even though the type is not, which is what the assertion in
// servicerpc.CheckResponse needs.
func (s rpcStatus) StatusCode() int32 { return s.Code }

// StatusReason implements servicerpc.ResponseStatusProvider.
func (s rpcStatus) StatusReason() string { return s.Reason }

// statusOf renders an error using this package's Error, so a code that reaches
// a client is the same code a local caller reads off the error.
func statusOf(err error) rpcStatus {
	code, reason := Error(err)
	return rpcStatus{Code: code, Reason: reason}
}

// --- wire types ---

// rpcEnterRequest is the Enter request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcEnterRequest struct {
	OwnerID int64        `json:"owner_id"`
	Req     EnterRequest `json:"req"`
}

// rpcEnterResponse is the Enter response on the wire.
type rpcEnterResponse struct {
	rpcStatus
	Run Run `json:"run"`
}

// rpcAttachRequest is the Attach request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcAttachRequest struct {
	OwnerID  int64    `json:"owner_id"`
	RunID    string   `json:"run_id"`
	Resource Resource `json:"resource"`
}

// rpcAttachResponse is the Attach response on the wire.
type rpcAttachResponse struct {
	rpcStatus
	Run Run `json:"run"`
}

// rpcFinishRequest is the Finish request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcFinishRequest struct {
	OwnerID int64  `json:"owner_id"`
	RunID   string `json:"run_id"`
	State   State  `json:"state"`
	Outcome string `json:"outcome"`
}

// rpcFinishResponse is the Finish response on the wire.
type rpcFinishResponse struct {
	rpcStatus
	Run Run `json:"run"`
}

// rpcLeaveRequest is the Leave request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcLeaveRequest struct {
	OwnerID int64  `json:"owner_id"`
	RunID   string `json:"run_id"`
	Reason  string `json:"reason"`
}

// rpcLeaveResponse is the Leave response on the wire.
type rpcLeaveResponse struct {
	rpcStatus
	Run Run `json:"run"`
}

// rpcGetRequest is the Get request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcGetRequest struct {
	OwnerID int64  `json:"owner_id"`
	RunID   string `json:"run_id"`
}

// rpcGetResponse is the Get response on the wire.
type rpcGetResponse struct {
	rpcStatus
	Run   Run  `json:"run"`
	Found bool `json:"found"`
}

// rpcCurrentRequest is the Current request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcCurrentRequest struct {
	OwnerID int64 `json:"owner_id"`
}

// rpcCurrentResponse is the Current response on the wire.
type rpcCurrentResponse struct {
	rpcStatus
	Run   Run  `json:"run"`
	Found bool `json:"found"`
}

// --- server ---

// RegisterHandlers publishes Session on a bus.
//
// It is called by the process that OWNS the service. The handlers decode and
// call the local implementation and contain no logic of their own: a check
// that lived here rather than in the service would apply only to remote
// callers, and a local caller would bypass it.
func RegisterHandlers(b bus.IBus, service Session) error {
	if b == nil {
		return fmt.Errorf("session: bus is nil")
	}
	if service == nil {
		return fmt.Errorf("session: service is nil")
	}
	handlers := map[string]bus.RpcHandlerFunc{
		MethodEnter: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcEnterRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcEnterResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, err := service.Enter(ctx.Context(), wire.OwnerID, wire.Req)
			return rpcEnterResponse{rpcStatus: statusOf(err), Run: run}, nil
		},
		MethodAttach: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcAttachRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcAttachResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, err := service.Attach(ctx.Context(), wire.OwnerID, wire.RunID, wire.Resource)
			return rpcAttachResponse{rpcStatus: statusOf(err), Run: run}, nil
		},
		MethodFinish: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcFinishRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcFinishResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, err := service.Finish(ctx.Context(), wire.OwnerID, wire.RunID, wire.State, wire.Outcome)
			return rpcFinishResponse{rpcStatus: statusOf(err), Run: run}, nil
		},
		MethodLeave: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcLeaveRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcLeaveResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, err := service.Leave(ctx.Context(), wire.OwnerID, wire.RunID, wire.Reason)
			return rpcLeaveResponse{rpcStatus: statusOf(err), Run: run}, nil
		},
		MethodGet: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcGetRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcGetResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, found, err := service.Get(ctx.Context(), wire.OwnerID, wire.RunID)
			return rpcGetResponse{rpcStatus: statusOf(err), Run: run, Found: found}, nil
		},
		MethodCurrent: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcCurrentRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcCurrentResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, found, err := service.Current(ctx.Context(), wire.OwnerID)
			return rpcCurrentResponse{rpcStatus: statusOf(err), Run: run, Found: found}, nil
		},
	}
	// Registered against Methods rather than by ranging the map, so a method
	// the interface declares and the table misses fails HERE, with a name.
	for _, method := range Methods {
		handler, ok := handlers[method]
		if !ok {
			return fmt.Errorf("session: no handler for %s", method)
		}
		if err := b.HandleRpc(method, handler); err != nil {
			return fmt.Errorf("session: register %s: %w", method, err)
		}
	}
	if len(handlers) != len(Methods) {
		return fmt.Errorf("session: %d handlers for %d methods", len(handlers), len(Methods))
	}
	return nil
}

// --- client ---

// DefaultCallTimeout bounds one RPC. A call with no timeout is a goroutine
// waiting on a process that may never answer.
const DefaultCallTimeout = 3 * time.Second

// BusClient is Session over a bus, for the processes that do not own this
// service.
//
// Its method signatures are the interface's, identity included: a caller still
// has to say whose identity it is, and the wire types are this type's
// implementation detail.
type BusClient struct {
	rpc *servicerpc.BusClient
}

// NewBusClient builds a client. serviceType empty means ServiceType; timeout
// non-positive means DefaultCallTimeout.
func NewBusClient(b bus.IBus, serviceType string, timeout time.Duration, opts ...servicerpc.Option) (*BusClient, error) {
	if b == nil {
		return nil, fmt.Errorf("session: bus is nil")
	}
	if serviceType == "" {
		serviceType = ServiceType
	}
	if timeout <= 0 {
		timeout = DefaultCallTimeout
	}
	return &BusClient{rpc: servicerpc.NewBusClient(b, serviceType, timeout, opts...)}, nil
}

func (c *BusClient) call(ctx context.Context, method string, req any, resp any) error {
	if c == nil || c.rpc == nil {
		return fmt.Errorf("session: client is not configured")
	}
	return c.rpc.CallChecked(ctx, 0, method, req, resp, "session call failed")
}

// Enter opens a run for an owner. Idempotent per RequestID, which is
// required: without it a retry allocates a second run, and the older one
// becomes unreachable.
// Enter implements Session.
func (c *BusClient) Enter(ctx context.Context, ownerID int64, req EnterRequest) (Run, error) {
	var resp rpcEnterResponse
	err := c.call(ctx, MethodEnter, rpcEnterRequest{
		OwnerID: ownerID,
		Req:     req,
	}, &resp)
	return resp.Run, err
}

// Attach records an external resource on a run, so releasing it later is
// walking a list rather than a hand-written unwind per failure path.
// Attach implements Session.
func (c *BusClient) Attach(ctx context.Context, ownerID int64, runID string, resource Resource) (Run, error) {
	var resp rpcAttachResponse
	err := c.call(ctx, MethodAttach, rpcAttachRequest{
		OwnerID:  ownerID,
		RunID:    runID,
		Resource: resource,
	}, &resp)
	return resp.Run, err
}

// Finish resolves a run to a terminal state the caller chooses and
// releases its resources.
// Finish implements Session.
func (c *BusClient) Finish(ctx context.Context, ownerID int64, runID string, state State, outcome string) (Run, error) {
	var resp rpcFinishResponse
	err := c.call(ctx, MethodFinish, rpcFinishRequest{
		OwnerID: ownerID,
		RunID:   runID,
		State:   state,
		Outcome: outcome,
	}, &resp)
	return resp.Run, err
}

// Leave abandons a run.
// Leave implements Session.
func (c *BusClient) Leave(ctx context.Context, ownerID int64, runID string, reason string) (Run, error) {
	var resp rpcLeaveResponse
	err := c.call(ctx, MethodLeave, rpcLeaveRequest{
		OwnerID: ownerID,
		RunID:   runID,
		Reason:  reason,
	}, &resp)
	return resp.Run, err
}

// Get reads a run. An elapsed deadline reads as expired before anything
// sweeps, so a caller never sees a run that is only open because nothing
// has resolved it yet.
// Get implements Session.
func (c *BusClient) Get(ctx context.Context, ownerID int64, runID string) (Run, bool, error) {
	var resp rpcGetResponse
	err := c.call(ctx, MethodGet, rpcGetRequest{
		OwnerID: ownerID,
		RunID:   runID,
	}, &resp)
	return resp.Run, resp.Found, err
}

// Current returns an owner's live run, if any. This is the index whose
// absence made a leaked run unreachable in the implementation this
// replaces.
// Current implements Session.
func (c *BusClient) Current(ctx context.Context, ownerID int64) (Run, bool, error) {
	var resp rpcCurrentResponse
	err := c.call(ctx, MethodCurrent, rpcCurrentRequest{
		OwnerID: ownerID,
	}, &resp)
	return resp.Run, resp.Found, err
}

// --- capability ---

// capability is what a Mod puts in the registry.
//
// It exists because converting to the interface at the registration call site
// does not do what it looks like it does: `Value: Session(x)` stores an any
// whose dynamic type is still x's — Go does not box an interface inside an
// interface — so an assertion on the concrete type succeeds anyway. Wrapping
// the interface in a struct makes the dynamic type this wrapper, which
// satisfies Session and nothing else.
//
// The consequence is the one that matters: a consumer cannot bind to the local
// implementation and then break on the day this service moves into its own
// process.
//
// It forwards each method explicitly rather than embedding the interface, and
// that is not style. Embedding names the field after the type, so an interface
// with a method of its own name — Rank.Rank, Match.Match — would have the
// field shadow the method and the wrapper would not satisfy the interface at
// all. The second service this generator ran against had exactly that shape.
type capability struct{ inner Session }

func (c capability) Enter(ctx context.Context, ownerID int64, req EnterRequest) (Run, error) {
	return c.inner.Enter(ctx, ownerID, req)
}

func (c capability) Attach(ctx context.Context, ownerID int64, runID string, resource Resource) (Run, error) {
	return c.inner.Attach(ctx, ownerID, runID, resource)
}

func (c capability) Finish(ctx context.Context, ownerID int64, runID string, state State, outcome string) (Run, error) {
	return c.inner.Finish(ctx, ownerID, runID, state, outcome)
}

func (c capability) Leave(ctx context.Context, ownerID int64, runID string, reason string) (Run, error) {
	return c.inner.Leave(ctx, ownerID, runID, reason)
}

func (c capability) Get(ctx context.Context, ownerID int64, runID string) (Run, bool, error) {
	return c.inner.Get(ctx, ownerID, runID)
}

func (c capability) Current(ctx context.Context, ownerID int64) (Run, bool, error) {
	return c.inner.Current(ctx, ownerID)
}

// Capability wraps a Session for registration. Both Mods use it, so the
// capability's dynamic type is the same whichever process published it.
func Capability(service Session) Session { return capability{inner: service} }

// OwnerCapabilities is what the owning Mod registers: the interface every
// consumer looks up, plus the owner-only name the Server looks up.
//
// Returned together so the two cannot be published apart. A process that
// registered the first and not the second would serve requests it cannot
// answer locally; one that registered the second and not the first would own a
// service nothing can find.
func OwnerCapabilities(service Session) []mods.Capability {
	wrapped := Capability(service)
	return []mods.Capability{
		{Name: CapabilityName, Value: wrapped},
		{Name: LocalCapabilityName, Value: wrapped},
	}
}

// --- capability name ---

// CapabilityName is the registry key both Mods publish under.
//
// It is declared here, from the interface's marker, so the name and the
// transport that depends on it are one fact. A repository that also keeps a
// central table of capability names should assert equality against this
// constant rather than repeat the string — two literals of the same name is
// how a Mod ends up ordered by one and looked up by the other.
const CapabilityName app.ModName = "service.session"

// LocalCapabilityName is published ONLY by the owning Mod, and it is how a
// process knows it owns this service.
//
// The alternative was to look up CapabilityName and ask whether the value is a
// *BusClient. That does not work, and finding out why is worth recording: the
// capability is deliberately wrapped so its dynamic type satisfies the
// interface and nothing else, which is exactly what defeats the assertion. The
// first version of this generator shipped that check, and the unit test for it
// passed only because it registered an unwrapped client — not what a Mod does.
//
// Asking "is the local implementation published here" is also the question
// that was actually meant. Type-sniffing for one particular remote
// implementation is a proxy for it, and a proxy that a wrapper, a test double
// or a future in-process forwarder each break differently.
const LocalCapabilityName app.ModName = "service.session.local"

// --- server ---

// Server is the app.Service for a process that runs Session on its own.
//
// Mod and Service are different concepts, not alternatives, and the generated
// split reflects that:
//
//	Mod:     Init(cfg) / Provide(registry) / Start() / Stop()
//	         PUTS capabilities into the registry. A process has many.
//	Service: Init(registry) / Serve(ctx) / Shutdown(ctx)
//	         TAKES capabilities out and then blocks. A process has exactly one.
//
// The app runs every Mod's Init, Provide and Start, and only then the
// Service's Init and Serve — so a Mod cannot block and a Service cannot be
// looked up by another process. A service that owns its own process needs
// both.
type Server struct {
	service Session
	bus     bus.IBus
}

// NewServer returns this service's app.Service.
func NewServer() *Server { return &Server{} }

// Name implements app.Service.
func (s *Server) Name() app.ServiceName { return app.ServiceName(ServiceType) }

// Service returns the local implementation, for the run hook.
func (s *Server) Service() Session { return s.service }

// Init takes what this process needs out of the registry and publishes the
// handlers.
//
// The handlers are registered HERE rather than in the Mod, and that is the
// decision that makes this process the owner: a Mod that registered them would
// publish this service's handlers in any process that happened to load it.
//
// It also refuses to run on a bus client. A process that serves Session
// over the bus while holding only a client to Session would forward every
// request to itself, and it would look like it was working until the first
// call.
func (s *Server) Init(r *app.Registry) error {
	service, ok := app.Lookup[Session](r, LocalCapabilityName)
	if !ok || service == nil {
		if _, remote := app.Lookup[Session](r, CapabilityName); remote {
			return fmt.Errorf("session server: %q is published but %q is not, so this "+
				"process holds a client to Session rather than the implementation — it would "+
				"forward every request to itself. Use session.NewMod() here and "+
				"session.NewClientMod() in the processes that call it",
				CapabilityName, LocalCapabilityName)
		}
		return fmt.Errorf("session server: capability %q not found; add session.NewMod()",
			LocalCapabilityName)
	}
	busClient, ok := app.Lookup[bus.IBus](r, mods.ModBus)
	if !ok || busClient == nil {
		return fmt.Errorf("session server: capability %q not found; a process that serves "+
			"Session needs a bus", mods.ModBus)
	}
	s.service, s.bus = service, busClient
	if err := RegisterHandlers(busClient, service); err != nil {
		return fmt.Errorf("session server: %w", err)
	}
	slog.Info("session server: handlers registered", "methods", len(Methods))
	return nil
}

// Serve blocks until the process is shutting down, running whatever periodic
// work this service has.
//
// The work itself is NOT generated: it calls run, which the author writes in a
// hand-written file. That is deliberate on both counts.
//
// It is here rather than in a Mod because every Mod in this design starts no
// goroutine — "how often does this deployment sweep" is a deployment decision,
// and a loop a Mod starts silently is a loop nobody can see failing. Serve has
// a context, has shutdown semantics, and its failure is the process's failure.
//
// And run is required even for a service with nothing periodic to do, rather
// than defaulted to a blocking no-op. Writing
//
//	func (s *Server) run(ctx context.Context) error { <-ctx.Done(); return nil }
//
// states "nothing periodic" in three lines. A generated default would answer
// the question by not asking it.
func (s *Server) Serve(ctx context.Context) error { return s.run(ctx) }

// Shutdown implements app.Service.
//
// Nothing is drained here: every operation this service exposes is
// synchronous, and the stores belong to the Mod that built them. A service
// that needs to drain should do it at the end of run, where the context that
// asked it to stop is in scope.
func (s *Server) Shutdown(context.Context) error { return nil }

var _ app.Service = (*Server)(nil)

// --- client mod ---

// ClientMod publishes a REMOTE Session capability, for the processes that
// call this service without owning it.
//
// It registers the same capability name and the same interface type the owning
// Mod does, which is the whole point: business logic looks up
// app.Lookup[Session] and is identical whether the service runs beside it or
// in another process. Choosing between the two Mods is the deployment
// decision, made once in a process's wiring, and no consumer sees it.
//
// They are mutually exclusive by construction: both publish CapabilityName, so
// the registry refuses the second. A process cannot end up holding both a
// local service and a client to itself with the winner decided by registration
// order.
type ClientMod struct {
	options []servicerpc.Option

	serviceType string
	timeout     time.Duration
	client      *BusClient
}

// NewClientMod returns a client Mod.
//
// options are passed to servicerpc: a deployment that needs a particular
// transport supplies it here, because that is a property of how this
// deployment routes rather than of the service.
func NewClientMod(options ...servicerpc.Option) *ClientMod {
	return &ClientMod{options: append([]servicerpc.Option(nil), options...)}
}

// Name implements app.Mod.
func (m *ClientMod) Name() app.ModName { return CapabilityName }

// DependsOn implements app.ModDependencyProvider.
func (m *ClientMod) DependsOn() []app.ModName { return []app.ModName{mods.ModBus} }

// Init reads configuration.
//
//	session:
//	  service_type: session   # optional, defaults to ServiceType
//	  call_timeout: 3s                 # optional, defaults to DefaultCallTimeout
//
// It reads no key prefix and no store settings, because a client has no store.
// A process that only calls this service therefore cannot be misconfigured
// with a prefix that disagrees with the owner's — it has no prefix to get
// wrong.
func (m *ClientMod) Init(cfg *viper.Viper) error {
	m.serviceType = cfg.GetString("session.service_type")
	if m.serviceType == "" {
		m.serviceType = ServiceType
	}
	// Read inline rather than through a shared helper, so the generated
	// transport depends on nothing but roost-core and roost-kit and works in
	// any repository.
	//
	// A negative value is refused rather than clamped: a caller that wrote -1
	// meant something, and silently reading it as the default hides the
	// mistake.
	m.timeout = DefaultCallTimeout
	if cfg.IsSet("session.call_timeout") {
		timeout := cfg.GetDuration("session.call_timeout")
		if timeout < 0 {
			return fmt.Errorf("session client mod: session.call_timeout must not be "+
				"negative, got %s", timeout)
		}
		if timeout > 0 {
			m.timeout = timeout
		}
	}
	return nil
}

// Provide builds the client and registers it.
func (m *ClientMod) Provide(r *app.Registry) error {
	busClient, ok := app.Lookup[bus.IBus](r, mods.ModBus)
	if !ok || busClient == nil {
		return fmt.Errorf("session client mod: capability %q not found; a process that calls "+
			"Session needs a bus", mods.ModBus)
	}
	client, err := NewBusClient(busClient, m.serviceType, m.timeout, m.options...)
	if err != nil {
		return fmt.Errorf("session client mod: %w", err)
	}
	m.client = client
	// Registered through Capability, so the dynamic type satisfies Session
	// and nothing else. A consumer that asserted on *BusClient would break in
	// the process that owns this service.
	return mods.RegisterAll(r, mods.Capability{Name: m.Name(), Value: Capability(client)})
}

// Start implements app.Mod. Nothing to start: the client holds no goroutine
// and the bus's lifecycle belongs to the bus Mod.
func (m *ClientMod) Start() error { return nil }

// Stop implements app.Mod. Nothing to stop, for the same reason.
func (m *ClientMod) Stop() {}

var _ app.Mod = (*ClientMod)(nil)

var (
	_ Session = (*BusClient)(nil)
	_ Session = capability{}
)
